language: python

sudo: false

matrix:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
    env: BUILD_DOCS=yes

before_install:
  - pip install pytest pytest-cov coveralls coverage
  - travis_retry gem install --version 0.8.9 faraday

install:
  - python setup.py install

script:
  - python -m pytest -vv --cov streamlink
  - bash script/pushdocs.sh

after_success:
  - sh .travis/build-win32.sh
  - coveralls
