language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script: python setup.py test
install:
  - pip install coveralls
  - pip install coverage
  - travis_retry gem install --version 0.8.9 faraday
after_success:
  - sh .travis/build-win32.sh
  - coveralls
